apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: import-test-go-xdxthjcv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: import-test-go-xdxthjcv 
  name: import-test-go-xdxthjcv
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: import-test-go-xdxthjcv
    weight: 100 
